sphamba/smear-cursor.nvim

lua/smear_cursor/animation.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, lua/smear_cursor/screen.lua
fixes #13
- use `vim.fn.screenrow()` and `vim.fn.screencol()` to get cursor position
- must use `vim.defer_fn`, otherwise past cursor position is returned, resulting in slower reaction time
- target cursor flickers more
=> Fix wrong smear placement with concealed characters

lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, lua/smear_cursor/init.lua
This PR builds further on the stylua PR:
- fixes issues with `:fclose!`, and other ways, where smear windows could become invalid
- it also uses the correct methods to set window/buffer options locally and without using deprecated APIs
=> refactor: window management

lua/smear_cursor/color.lua, lua/smear_cursor/draw.lua
Use the `blend` property of hl groups to prevent needing to set `winblend` on every character draw.
Works with or without legacy symbols.
Builds on the wins PR. Actual changes: https://github.com/sphamba/smear-cursor.nvim/commit/335ae3f7cb542bb4973b077624d62a372c813511
=> perf: use blnd hl groups

lua/smear_cursor/draw.lua
Another small PR to optimize two extra things:
- use a fixed extmark id that can be deleted faster than using clear namespace
- use win hide on Neovim >= 0.10 to prevent needing to clear and move the window
=> perf: use win hide on Neovim >= 0.10 and a fixed extmark id for faster clearing

lua/smear_cursor/color.lua, lua/smear_cursor/events.lua, lua/smear_cursor/init.lua
When `cursor_color = "none"`, we try using the color at the cursor's hl group as the cursor color.
This is similar to how kitty does the smearing cursors, with `cursor none`, meaning it takes the color of what's at the current cell as the cursor color.
When getting the color, we first try treesitter captures if treesitter highlighting is enabled in the buffer and then fallback to extmarks. Regular treesitter extmarks are ephemeral, so they can't be retrieved with the get extmarks function.
Everything is cached, so should not impact performance.
I believe you tried something similar, as there was a non-used function called `M.get_hl_group` already :)
I used some metatable magic to prevent making changes in other places where the hl group lookup tables were used. Let me know if you'd rather …
=> feat(colors): optionally get the cursor color from the hl group at the cursor

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Smear between two windows to the same screen line even if `smear_between_neighbor_lines = true`
- fix #31
=> fix: smear between windows on same screen line

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, tests/test_draw_quad.lua
- remove `draw_line` and used functions
- add `draw_quad`
- render smear as quad instead of two linked rectangles
- necessary for #7 and #33
- fix #34
=> feat: render smear as quad

lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua
Add a configuration option to enable smear for vertical bar cursor in Normal mode.
Doesn't look very nice due to the coarsness of rendering.
- add `vertical_bar_cursor` bool option
- fix #33
=> feat: somewhat support vertical bar cursor

.github/workflows/docs.yml, doc/smear-cursor.nvim.txt
Explain the purpose and scope of your contribution.
- add GitHub action for generating vim docs
- since your README is very detailed, and your code comments not so much, I figured this is the right action for this project (it transforms the contents of the README to vimdoc format, enabling users to access it via `:help smear-cursor.nvim.txt`)
- **note:** This is only a suggestion PR, if you don't like it or want me to add/change something let me know
- fix #8
=> ci(docs): add gh actions for generating vimdocs

lua/smear_cursor/draw.lua
Add a filetype to buffers used to render the smears. Allow for filtering out these buffers in other plugins
- add buffer filetype for filtering
- fix #42
=> fix: add buffer filetype for filtering

lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua
Check windows every time they are needed or cleared.
- fix: limit number of windows kept open
- add: limit number of windows kept open
- may adress #42
=> fix: invalid window id

lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua
Add maximum smear length to prevent lagging.
- related to #54
=> perf: add max smear length

lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Add list of filetypes where smear is disabled
- add config option `filetypes_disabled = {}`
- fix #53
=> feat: add list of filetypes where smear is disabled

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, lua/smear_cursor/screen.lua
When scrolling in a buffer, show the smear from the previous buffer position instead of the previous screen position.
- add config parameter `scroll_buffer_space` (`true` by default).
- fix #40 and #51
=> feat:scroll buffer space

lua/smear_cursor/animation.lua
Show smear on `zz`, `zt` and `zb` movements even when `smear_buffer_space` is set to `true` by checking if the current line has changed or not.
- fix #62
=> fix: smear on zz zt zb movements

README.md, lua/smear_cursor/color.lua, lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, lua/smear_cursor/init.lua
Add default and configurable cterm color gradient. Example:
```lua
opts = {
cterm_cursor_colors = { 240, 245, 250, 255 },
cterm_bg = 235,
}
```
- add `cterm_cursor_colors` and `cterm_bg` configuration variables
- fix #50
=> feat:cterm colors

lua/smear_cursor/color.lua
Remove too strict condition that prevents the processing of "none" `cursor_cursor`
- fix #68
- close #69
=> fix: restore "none" cursor_color processing

lua/smear_cursor/animation.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua
Use `vim.uv` timer intervals instead of timeouts for animation, which doesn't freeze when opening the command line.
- replace `vim.defer_fn(animate, config.time_interval)` with `timer:start(0, config.time_interval, vim.schedule_wrap(animate))`
- remove drawing of previous smear on fast cursor move to avoid random jumps
- add smear to command line and command window
- fix #9
- fix one case of #15
=> Feat: smear to command line

lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Add a delay between detected events and starting of the animation, in case the target changes rapidly.
Happens when hitting keybindings that rapidly trigger `CmdlineEnter`, `CmdlineChanged`, and `CmdlineLeave` events.
- add delay before starting animation
- add `delay_animation_start` configuration parameter, default to `5` milliseconds
- fix #73
- fix #74
=> fix: jump to cmd line when hitting some keybindings

lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Add `smear_to_cmd` configuration parameter, controlling whether `CmdlineEnter,CmdlineChanged,CmdwinLeave` events are listened. `true` by default.
=> feat: add parameter to enable/disable smear to cmd line

lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Use (deferred) `vim.api.nvim_get_mode()` to choose how to compute the cursor position, instead of relying on the triggering neovim event.
- change `delay_animation_start` to 0 milliseconds by default. Perhaps not needed anymore.
- fix #79
=> chore: simplify autocmd for command line events

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua
Add minimum smear activation distances (horizontal and vertical) with parameters `min_horizontal_distance_smear` and `min_vertical_distance_smear` set to 0 by default.
- fix #83
=> feat: add minimum smear activation distances

lua/smear_cursor/animation.lua
Prevent a potential calculation that would result in NaN in cursor corner coordinates.
- may fix #87
=> fix: possible NaN corners

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua, lua/smear_cursor/events.lua, lua/smear_cursor/screen.lua
Add smear animations in insert mode (enabled by default). Accounts for transitions between normal and insert mode.
- add smear in insert mode
- add configuration options (behavior and animation settings) for insert mode
- add vertical bar characters (for fonts supporting legacy computing symbols)
- add a duration the cursor must stay still before triggering animation: `delay_event_to_smear`, default 1 millisecond
- fix #72
=> feat: smear insert mode

lua/smear_cursor/screen.lua
Added noice command palette support.
noice.nvim exposes `vim.g.ui_cmdline_pos`  varibale for command palette position.
- change `get_screen_cmd_cursor_position()` 
- fix #76
=> feat: smear to noice.nvim command_palette

lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Add trigger of smear animation using `vim.on_key()`.
- fix #12
=> feat: add arbitrary key press detection

lua/smear_cursor/screen.lua
In the latest update (v0.4.0), opening `noice.nvim`'s command_palette will results in following error:
```
Error executing vim.schedule lua callback: .../nvim/lazy/smear-cursor.nvim/lua/smear_cursor/screen.lua:22: attempt to perform arithmetic on a nil value
stack traceback:
.../nvim/lazy/smear-cursor.nvim/lua/smear_cursor/screen.lua:22: in function 'get_screen_cmd_cursor_position'
.../nvim/lazy/smear-cursor.nvim/lua/smear_cursor/events.lua:24: in function 'move_cursor'
.../nvim/lazy/smear-cursor.nvim/lua/smear_cursor/events.lua:59: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
I traced back to commit 2d6fa78 which introduced this problem. 
change: accessing `vim.g.ui_cmdline_pos` using string instead of index
=> fix: noice.nvim getting cmdline_pos results in nil value

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/color.lua, lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Use `vim.o.guicursor` to hide the real cursor, instead of printing a block character at the target location.
- change `hide_target_hack` to `false` by default. May be set to `true` for non-users of `termguicolors`
- fix visible smear in replace mode
=> feat: use vim.o.guicursor to hide real cursor

lua/smear_cursor/events.lua
fixes #99 
Looks like this occurs when jumping from one ignored buffer to another (or if the event fires twice?).
The group is already deleted, so it attempts to delete it again, resulting in the error. 
~~The fix is to check whether the group exists first with `pcall` before deleting.~~
We can use the `nvim_clear_autocmds` API in place of deleting to resolve this. Even if no autocmds are removed, no error will occur.
=> fix(events): clear augroup instead of deleting

lua/smear_cursor/animation.lua
Prevent permanent hidden cursor when using [Neoscroll](https://github.com/karb94/neoscroll.nvim) in conjunction with smear-cursor.nvim
=> fix: disappearing cursor when using neoscroll

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/color.lua
Only append a hl group to `vim.o.guicursor` instead of hard setting it. Should fix bad interactions with other plugins changing its value.
- fix #101
=> fix: interaction with other plugins modifying vim.o.guicursor

lua/smear_cursor/config.lua, lua/smear_cursor/events.lua
Add option `smear_terminal_mode` to toggle smear in terminal mode.
- disable smear in terminal mode by default
- change default `delay_after_key` from 1ms to 5ms
- fix #105 
- fix #106
=> feat: terminal mode toggler

lua/smear_cursor/events.lua
See title.
- remove specific `move_cursor_insert_mode` in `events.lua`
- fix #109
=> fix: treat insert mode the same way as replace and terminal modes

lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua
Add toggles for smear directions:
- `smear_horizontally` (default `true`)
- `smear_vertically` (default `true`)
- `smear_diagonally` (default `true`)
- may fix #112
=> feat: add toggles for smear directions

lua/smear_cursor/animation.lua
Prevent smearing when disabled in config, even when moving in fast succession.
May not work perfectly as intended yet (sometimes, the smear does not trigger even if it should).
Affected options:
- `smear_between_neighbor_lines`
- `min_vertical_distance_smear`
- `min_horizontal_distance_smear`
- `smear_horizontally`
- `smear_vertically`
- `smear_diagonally`
=> fix: prevent disabled smears when moving in fast succession

README.md, lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua, lua/smear_cursor/draw.lua
Add configuration option allowing to get a smooth block cursor the trail.
- add `never_draw_over_target` option (default `true`)
- add videos in readme
=> feat: smooth block cursor without smear

lua/smear_cursor/animation.lua
Prevent immediate hiding of real cursor on `CursorMoved` event depending on current mode.
- fix #124
=> fix: disappearing cursor in disabled modes

lua/smear_cursor/animation.lua, lua/smear_cursor/events.lua
Some keybindings (_e.g._ `fx`, `%`) and plugins (_e.g._ guns/vim-sexp) cause nvim mode to briefly switch to cmd mode when the cursor moves. Previous smear-cursor behavior was to systematially jump when detecting cmd mode, which sometimes caused jumps (absence of animation) when the keybindings were hit. Removed jumping and only trigger redraw (needed in cmd mode) when smear is outside of the cmd line zone.
- fix #129
=> fix: don't systematically jump when briefly in cmd mode

lua/smear_cursor/animation.lua, lua/smear_cursor/config.lua
Add initial animation velocity in direction opposite to target, controlled by `anticipation` parameter (default `0.55`)
- fix #37
=> feat: add anticipation to animation

lua/smear_cursor/draw.lua
=> fix: #148 Define the border option as 'none' to impede the creation of windows with borders
